apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      component: nginx
resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: hamrss-nginx-config
    files:
      - files/default.conf
